apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
  namespace: application1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-app
